ALTER TYPE "WasteRuleType" ADD VALUE 'VM_MISSING_COMMITMENT_COVERAGE';
ALTER TYPE "WasteRuleType" ADD VALUE 'ORPHANED_NAT_GATEWAY';
ALTER TYPE "WasteRuleType" ADD VALUE 'DEVTEST_SPOT_ELIGIBLE';
ALTER TYPE "WasteRuleType" ADD VALUE 'SCHEDULE_REQUIRED_BUT_MISSING';
ALTER TYPE "WasteRuleType" ADD VALUE 'ARCHITECTURE_REVIEW_REQUIRED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AUTOMATION_EXPIRED_RESOURCE';
