ALTER TYPE "WasteRuleType" ADD VALUE 'BACKUP_VAULT_UNUSED';
ALTER TYPE "WasteRuleType" ADD VALUE 'BACKUP_ORPHANED_ITEM';
ALTER TYPE "WasteRuleType" ADD VALUE 'BACKUP_OLD_RECOVERY_POINT';
ALTER TYPE "WasteRuleType" ADD VALUE 'BACKUP_RETENTION_EXCESSIVE';
