ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_SHARE_UNUSED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_PREMIUM_OVERSIZED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_QUOTA_OVERSIZED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_PROTECTION_EXCESSIVE';
