ALTER TYPE "WasteRuleType" ADD VALUE 'COST_ANOMALY_DETECTED';
ALTER TYPE "WasteRuleType" ADD VALUE 'FORECAST_ACTIONABLE_FINDING';
ALTER TYPE "WasteRuleType" ADD VALUE 'UNIT_ECONOMICS_REVIEW';
ALTER TYPE "WasteRuleType" ADD VALUE 'ROI_PRIORITIZATION';
