-- AlterEnum
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_SESSION_HOST_LOW_UTILIZATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_HOSTPOOL_EXCESS_HOSTS';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_HOSTPOOL_LOW_DENSITY';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_SESSION_HOST_PREMIUM_DISK_UNUSED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_SCALING_PLAN_MISSING';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_SCALING_PLAN_DISABLED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_HOST_RUNNING_OUTSIDE_SCALING_WINDOW';
ALTER TYPE "WasteRuleType" ADD VALUE 'AVD_PERSONAL_HOST_UNUSED';
