-- AlterEnum
ALTER TYPE "WasteRuleType" ADD VALUE 'VM_MISSING_HYBRID_BENEFIT';
ALTER TYPE "WasteRuleType" ADD VALUE 'VM_MISSING_LINUX_BYOL';
ALTER TYPE "WasteRuleType" ADD VALUE 'VM_OUTDATED_SKU_GENERATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'VM_STOPPED_RETAINING_RESOURCES';

-- CreateEnum
CREATE TYPE "SavingsCategory" AS ENUM ('HARD_SAVING', 'POTENTIAL_SAVING');

-- AlterTable
ALTER TABLE "WasteFinding" ADD COLUMN "savingsCategory" "SavingsCategory",
ADD COLUMN "metricObserved" DOUBLE PRECISION,
ADD COLUMN "periodAnalyzedDays" INTEGER;
