-- AlterEnum
ALTER TYPE "WasteRuleType" ADD VALUE 'DISK_IDLE_LOW_UTILIZATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'DISK_PREMIUM_TIER_UNNECESSARY';
ALTER TYPE "WasteRuleType" ADD VALUE 'DISK_PREMIUM_V2_OVERSIZED';
ALTER TYPE "WasteRuleType" ADD VALUE 'DISK_TIER_OVERSIZED';
ALTER TYPE "WasteRuleType" ADD VALUE 'DISK_NONPROD_PREMIUM';
ALTER TYPE "WasteRuleType" ADD VALUE 'SNAPSHOT_ORPHANED_SOURCE';
ALTER TYPE "WasteRuleType" ADD VALUE 'SNAPSHOT_EXCESSIVE_COUNT';
ALTER TYPE "WasteRuleType" ADD VALUE 'IMAGE_ORPHANED';
ALTER TYPE "WasteRuleType" ADD VALUE 'GALLERY_IMAGE_VERSION_OLD';
