ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_OLD_HOT_TIER';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_COOL_TIER_UNUSED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_DUPLICATED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_FSLOGIX_OVERSIZED';
ALTER TYPE "WasteRuleType" ADD VALUE 'AZURE_FILES_ALTERNATIVE_SERVICE_CHEAPER';
