-- AlterEnum
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_NO_AUTOSCALE';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_MAX_INSTANCES_HIGH';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_AUTOSCALE_NO_SCALE_IN';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_IDLE_LOW_UTILIZATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_SCALEOUT_METRIC_INADEQUATE';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_NONPROD_NO_SCHEDULE';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_OUTDATED_SKU_GENERATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_SPOT_ELIGIBLE';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_MISSING_SAVINGS_PLAN_OR_RESERVATION';
ALTER TYPE "WasteRuleType" ADD VALUE 'VMSS_OUTDATED_MODEL_INSTANCES';
